name: CranberriPlugin
version: 1.0.0
main: jupiterpi.cranberri.CranberriPlugin
description: Cranberri Server Plugin
author: JupiterPi
api-version: 1.19

commands:
  cranberri:
    description: Gives you the Cranberri tool.
    usage: /cranberri, /cranberri (tool|logger)
    aliases: [cb]